name: check link

on:
  schedule:
    - cron: '0 * * * *'
    - cron: '5 * * * *'
    - cron: '10 * * * *'
    - cron: '15 * * * *'
    - cron: '20 * * * *'
    - cron: '25 * * * *'
    - cron: '30 * * * *'
    - cron: '35 * * * *'
    - cron: '40 * * * *'
    - cron: '45 * * * *'
    - cron: '50 * * * *'
    - cron: '55 * * * *'

jobs:
  build:
    name: check link
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: check link
        run: |
          echo "::set-output name=check-link::$(bundle exec bin/check_link.rb)\n"
        id: run_check
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{ steps.run_check.outputs.* }}
          SLACK_WEBHOOK: ${{ secrets.CHECK_LINK_SLACK_WEBHOOK }}
