name: check link

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: check link
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Timezone
        run: |
          sudo timedatectl set-timezone Asia/Tokyo
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: check link
        run: bundle exec bin/check_link.rb
        env:
          SLACK_WEBHOOK: ${{ secrets.CHECK_LINK_SLACK_WEBHOOK }}
