name: data bot

on:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  build:
    name: Google Sheets to JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
      - name: Setup Timezone
        run: |
          sudo timedatectl set-timezone Asia/Tokyo
      - name: Generate JSON
        run: |
          cd data_tools/google_sheets_to_data_json/
          bundle install
          echo $GOOGLE_SHEETS_TO_DATA_JSON_CREDENTIALS_JSON | base64 --decode > credentials.json
          echo $GOOGLE_SHEETS_TO_DATA_JSON_TOKEN_YAML | base64 --decode > token.yaml
          ruby generate_data_json.rb
        shell: bash
        env:
          GOOGLE_SHEETS_TO_DATA_JSON_CREDENTIALS_JSON: ${{secrets.GOOGLE_SHEETS_TO_DATA_JSON_CREDENTIALS_JSON}}
          GOOGLE_SHEETS_TO_DATA_JSON_TOKEN_YAML: ${{secrets.GOOGLE_SHEETS_TO_DATA_JSON_TOKEN_YAML}}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data
          git commit -m "[BOT] JSON"
      - name: Push changes to develop
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
